// <auto-generated />
namespace Shop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mise_a_jour_model_bookexchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mise_a_jour_model_bookexchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202112201326385_Mise_a_jour_model_bookexchange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
