// <auto-generated />
namespace Shop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class maj_db_set_bookexchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(maj_db_set_bookexchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202112201344218_maj_db_set_bookexchange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
