// <auto-generated />
namespace Shop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class maj_methode_validate_exchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(maj_methode_validate_exchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202112201417404_maj_methode_validate_exchange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
